from pyautogui import keyDown,keyUp
from time import sleep 

print('start')
sleep(10)
def 移動1():
    keyDown('esc')
    keyUp('esc')
    sleep(10)
    keyDown('right')
    sleep(20)
    keyUp('right')
    sleep(1)
    keyDown('up')
    sleep(1)
    keyUp('up')
    sleep(1)
    keyDown('right')
    sleep(40)
    keyUp('right')

def 移動2():
    keyDown('right')
    sleep(3)
    keyUp('right')
    sleep(15)
    keyDown('right')
    sleep(14)
    keyUp('right')
    sleep(1)
    keyDown('q')
    keyDown('right')
    sleep(10)
    keyUp('q')
    keyUp('right')
    sleep(5)
    keyDown('up')
    sleep(1)
    keyUp('up')
    sleep(1)
    a= 0
    while a != 2:
        keyDown('up')
        sleep(1)
        keyUp('up') 
        sleep(1)
        a += 1
    keyDown('right')
    sleep(13)
    keyUp('right')
    sleep(1)
    keyDown('left')
    sleep(10)
    keyUp('left')
    sleep(1)
    keyDown('q')
    keyDown('right')
    sleep(10)
    keyUp('q')
    keyUp('right')
    sleep(1)
    keyDown('up')
    sleep(1)
    keyUp('up')
    sleep(1)
    keyDown('right')
    keyDown('up')
    sleep(1)
def 移動3():
    keyUp('right')
    keyUp('up')
    sleep(1)
    keyDown('right')
    sleep(10)
    keyUp('right')
    
def 移動4():
    keyDown('right')
    sleep(9.5)
    keyDown('up')
    sleep(1)
    keyUp('up')
    keyUp('right')
    keyDown('up')
    sleep(10)
    keyUp('up')
    sleep(1)
    keyDown('right')
    sleep(30)
    keyUp('right')

def 移動5():
    keyDown('right')
    sleep(10.9)
    keyUp('right')
    sleep(1)
    keyDown('left')
    sleep(10)
    keyUp('left')
    sleep(5)
    keyDown('right')
    sleep(27.5)
    keyDown('up')
    sleep(1)
    keyUp('up')
    sleep(5)
    keyUp('right')
    sleep(3)
    keyDown('right')
    sleep(2.9)
    keyDown('up')
    sleep(1)
    keyUp('up')
    sleep(12.5)
    keyDown('up')
    sleep(1)
    keyUp('up')
    sleep(5)
    keyUp('right')
    sleep(1)
    keyDown('up')
    keyDown('right')
    sleep(7)
    keyUp('up')
    keyUp('right')
    sleep(1)
    keyDown('down')
    keyDown('right')
    sleep(5)
    keyUp('down')
    keyDown('up')
    sleep(50)
    keyUp('right')
    keyUp('up')
    
    




    

    


移動1()
移動2()
移動3()
移動4()
移動5()

